version: '3'

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=America/Mexico_City
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - QDRANT__SERVICE__API_KEY
    volumes:
      - ./data:/home/node/.n8n
    networks:
      - n8n-net

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:v1.9.2
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__API_KEY: "miapikey"
    networks:
      - n8n-net

volumes:
  n8n_data:
  qdrant_storage:

networks:
  n8n-net:
    driver: bridge